Repository PelletierConstructionGroup/pelletier-construction-group-nextjs, pull requests merged in 2024-11, with the labels that each got.

#62 carousel timeout minor adjustment for the user to have enough time to read
  app/testimonials/page.tsx
  package-lock.json
Labels: enhancement, Sprint 14

#49 pelletier-group-nextjs-12-90-Builder-Page
  app/blueprint/page.tsx
  components/Navbar.tsx
Labels: Sprint 12

#70 Added header image and styling to the contact page
  app/contact/page.tsx
Labels: enhancement, Sprint 15
