Repository PelletierConstructionGroup/pelletier-construction-group-nextjs, pull requests merged in 2025-01, with the labels that each got.

#77 Pelletier_16_76_navigation-bar
  components/Navbar.tsx
  package-lock.json
Labels: enhancement

#80 PCG_16_79-Add-Hero-Component
  app/estimates/page.tsx
  components/Hero.tsx
Labels: enhancement

#78 PCG_16_73_Feature-Clickable-Image
  app/projects-page/[projectname]/page.tsx
  app/projects-page/page.tsx
  app/projects-page/projects.json
Labels: Sprint 16

#83 pelletier-construction-group-nextjs _16_82_GitHub_actions_adjustment
  .github/workflows/auto-assign-issues.yml
  .github/workflows/on-new-issue.yaml
  post-issue-smartsheet.py
Labels: bug

#85 pelletier-construction-group-nextjs _16_82_GitHub_actions_adjustment_patch
  post-issue-smartsheet.py
Labels: bug
