Repository PelletierConstructionGroup/pelletier-construction-group-nextjs, pull requests merged in 2025-06, with the labels that each got.

#113 Bug Fix: Resolve Layout and Responsiveness Issues on Home, Testimonials, Contact pages and hero component
  app/contact/page.tsx
  app/page.tsx
  app/testimonials/page.tsx
  components/Carousel.tsx
  components/Hero.tsx
Labels: bug

#115 Standardize Page Header Layouts: Fix Image/Text Bleed & Unify Styling Across Pages (Issue #114)
  app/about/page.tsx
  app/estimates/page.tsx
  app/page.tsx
  components/Hero.tsx
Labels: enhancement

#119 pelletier-construction-group-nextjs_sprint#24-issue#118-edited-hero-image-for-estimate-page
  app/estimates/page.tsx
Labels: Sprint 24

#121 pelletier-construction-group-nextjs_sprint#24_issue#120_change-adu-placeholder-image
  app/dadu/dadus.json
Labels: Sprint 24
